name: Deploy page

on:
  pull_request:
    branches: ["qa"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Render Deploy Action
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{secrets.serviceid}}
          api-key: ${{secrets.apikey}}
